#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing upload::git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading llvm
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf llvm.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/llvm.tar searchfox.repositories llvm.tar
rm llvm.tar
popd

echo "Performing upload::blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading llvm blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf llvm-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/llvm-blame.tar searchfox.repositories llvm-blame.tar
rm llvm-blame.tar
popd
