#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing upload::git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading comm-esr68
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf comm-esr68.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/comm-esr68.tar searchfox.repositories comm-esr68.tar
rm comm-esr68.tar
popd

echo "Performing upload::blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading comm-esr68 blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf comm-esr68-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/comm-esr68-blame.tar searchfox.repositories comm-esr68-blame.tar
rm comm-esr68-blame.tar
popd
