#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Uploading comm-esr68
pushd $INDEX_ROOT
tar cf comm-esr68.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/comm-esr68.tar searchfox.repositories comm-esr68.tar
rm comm-esr68.tar
popd

date

echo Uploading comm-esr68 blame
pushd $INDEX_ROOT
tar cf comm-esr68-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/comm-esr68-blame.tar searchfox.repositories comm-esr68-blame.tar
rm comm-esr68-blame.tar
popd

date
