#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Uploading comm-esr128
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf comm-esr128.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/comm-esr128.tar searchfox.repositories comm-esr128.tar
rm comm-esr128.tar
popd

date

echo Uploading comm-esr128 blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf comm-esr128-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/comm-esr128-blame.tar searchfox.repositories comm-esr128-blame.tar
rm comm-esr128-blame.tar
popd

date
