#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# ESR91 no longer has taskcluster/treeherder jobs and so we no longer can use it
# for semantic indexing.

