#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# See ../mozilla-central/setup for documentation

REVISION_TREE=mozilla-esr91
REVISION_ID=latest

date

source $CONFIG_REPO/shared/resolve-gecko-revs.sh $REVISION_TREE $REVISION_ID

date

$CONFIG_REPO/shared/checkout-gecko-repos.sh $REVISION_TREE "esr91" "$INDEXED_HG_REV"

date

$CONFIG_REPO/shared/fetch-tc-artifacts.sh $REVISION_TREE $INDEXED_HG_REV "$PREEXISTING_HG_REV"

date
