#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# See ../mozilla-central/setup for documentation

# ESR91 isn't getting any new commits, so we can hard-code the last revision
# for simplicity in checkout-gecko-repos.sh.
$CONFIG_REPO/shared/checkout-gecko-repos.sh "mozilla-esr91" "esr91" "f21620428eb73c49891ba403bdb4ed799dc32c21"

