#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Uploading ecma262
pushd $INDEX_ROOT
tar cf ecma262.tar git
python $AWS_ROOT/upload.py $INDEX_ROOT/ecma262.tar searchfox.repositories ecma262.tar
rm ecma262.tar
popd

date

echo Uploading ecma262 blame
pushd $INDEX_ROOT
tar cf ecma262-blame.tar ecma262-blame
python $AWS_ROOT/upload.py $INDEX_ROOT/ecma262-blame.tar searchfox.repositories ecma262-blame.tar
rm ecma262-blame.tar
popd

date
