#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing upload::git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading ecma262
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf ecma262.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/ecma262.tar searchfox.repositories ecma262.tar
rm ecma262.tar
popd

echo "Performing upload::blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading ecma262 blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf ecma262-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/ecma262-blame.tar searchfox.repositories ecma262-blame.tar
rm ecma262-blame.tar
popd
