#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# See ../mozilla-central/setup for documentation

REVISION_TREE=mozilla-beta
REVISION_ID=latest
TRY_GIT_REV=

date

source $CONFIG_REPO/shared/resolve-gecko-revs.sh $REVISION_TREE $REVISION_ID

date

$CONFIG_REPO/shared/checkout-gecko-repos.sh $REVISION_TREE "beta" "$INDEXED_HG_REV"

date

pushd $INDEX_ROOT
$CONFIG_REPO/shared/fetch-tc-artifacts.sh $REVISION_TREE $INDEXED_HG_REV
popd

date
