#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

if [[ $# != 2 ]]; then
    echo "Usage: $0 <config-repo-dir> <out-file>"
    exit 1
fi

CONFIG_REPO_DIR=$1
OUT_FILE=$2

$CONFIG_REPO_DIR/build-help-and-tree-list.py help $CONFIG_REPO_DIR $OUT_FILE
