#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# See ../mozilla-central/setup for documentation

REVISION_TREE=enterprise-firefox.branch.enterprise-main
REVISION_ID=latest

date

source $CONFIG_REPO/firefox-shared/resolve-gecko-revs.sh $REVISION_TREE $REVISION_ID

# enterprise-firefox is pure git-based repository and the result of
# resolve-gecko-revs.sh script is actually the git revision.
INDEXED_GIT_REV=$INDEXED_HG_REV
INDEXED_HG_REV=-
PREEXISTING_GIT_REV=$PREEXISTING_HG_REV
PREEXISTING_HG_REV=-

date

$CONFIG_REPO/firefox-shared/checkout-gecko-repos.sh $REVISION_TREE "enterprise-main" - "$INDEXED_GIT_REV"

date

$CONFIG_REPO/firefox-shared/fetch-tc-artifacts.sh $REVISION_TREE $INDEXED_GIT_REV "$PREEXISTING_GIT_REV"

date
