#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

# the starting point for the build logic here is from:
# https://github.com/dpino/webkit-index-config/blob/master/webkit/build
#
# our primary changes here are:
# - we handle the dependencies and flatpak updating in `setup` so that we can
#   persist the downloaded flatpak state in `upload` because the flatpak server
#   seems to only be able to talk to our AWS instances at very slow speeds like
#   600kB/s.  (It started faster and goes downhill from there.  We're talking
#   hours for a full download, though.)
# - we dump the indexer setup to "config" like other build scripts so we can
#   look at it afterwards rather than sourcing it directly.

date

# Add the special clang flags.
$MOZSEARCH_PATH/scripts/indexer-setup.py > $INDEX_ROOT/config
. $INDEX_ROOT/config

mkdir -p $OBJDIR
cd $OBJDIR

# Default WebKit port.
PORT=${PORT:-GTK}

# C Flags are encoded into CC var.
# Remove prefix (clang) and store flags into C_FLAGS.
C_FLAGS=${CC:6}
CC=${CC:0:5}

# CXX Flags are encoded into CXX var.
# Remove prefix (clang++) and store flags into CXX_FLAGS.
CXX_FLAGS=${CXX:8}
CXX=${CXX:0:7}

date

# Rationales:
# - `-DDEVELOPER_MODE=ON`: evolution of `-DENABLE_GPU_PROCESS=OFF` for the
#   purposes of avoiding the linker issue in
#   https://bugs.webkit.org/show_bug.cgi?id=275110 but which also aligns us more
#   closely with how the upstream webkit ubuntu builders we depend on for
#   detecting good revisions actually build.  They actually use
#   https://searchfox.org/wubkat/source/Tools/Scripts/build-webkit which gets
#   the arg pushed by default in `webkitdirs.pm`.
#   - https://github.com/mozsearch/mozsearch-mozilla/pull/262 holds discussion
# - `-DENABLE_DOCUMENTATION=OFF -DENABLE_INTROSPECTION=OFF`: Disables gi-docgen
#   which fails intermittently for some reason.
#   - https://github.com/mozsearch/mozsearch-mozilla/pull/262 holds discussion

cmake $FILES_ROOT \
    -DCMAKE_C_COMPILER="$CC" \
    -DCMAKE_CXX_COMPILER="$CXX" \
    -DCMAKE_C_FLAGS="$C_FLAGS" \
    -DCMAKE_CXX_FLAGS="$CXX_FLAGS" \
    -DUSE_WPE_RENDERER=OFF \
    -DUSE_LCMS=OFF \
    -DUSE_JPEGXL=OFF \
    -DUSE_LIBBACKTRACE=OFF \
    -DENABLE_BUBBLEWRAP_SANDBOX=OFF \
    -DCMAKE_BUILD_TYPE=Debug \
    -DPORT=$PORT \
    -DUSE_SYSTEM_SYSPROF_CAPTURE=OFF \
    -DDEVELOPER_MODE=ON \
    -DENABLE_SPEECH_SYNTHESIS=OFF \
    -DENABLE_DOCUMENTATION=OFF \
    -DENABLE_INTROSPECTION=OFF

date

make -j$(nproc)
cd -

date

# Webkit does something weird where it ends up with duplicate copies of some
# header files in OBJDIR/WebCore/PrivateHeaders/.  It seems like they're
# installed there and both the original and the private headers end up with
# equivalent analysis records.  Based on extremely cursory investigation, only
# the source-tree file has actual include usages.  But since only the source
# tree has blame history and is permalink-able, it seems reasonable to nuke the
# private headers' analysis data to avoid them breaking "go to definition" and
# "go to declaration".
rm -rf $INDEX_ROOT/analysis/WebCore/PrivateHeaders
