#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing setup::download-git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

# Note that our tarball here also includes the flatpak SDK downloads that live
# under git/WebKitBuild/UserFlatpak.
echo Downloading webkit
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing git folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/wubkat.tar.lz4
    lz4 -dc wubkat.tar.lz4 | tar -x
    rm wubkat.tar.lz4
fi
popd

echo "Performing setup::download-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading webkit blame
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/wubkat-blame.tar.lz4
    lz4 -dc wubkat-blame.tar.lz4 | tar -x
    rm wubkat-blame.tar.lz4
fi
popd

echo "Performing setup::git-pull step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Updating git
pushd $GIT_ROOT
git remote prune origin || true
git pull origin main || handle_tree_error "wubkat git pull"
popd

echo "Performing setup::last-successful-build-to-git-commit step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Figuring out what revision to use.
USE_REV=$($CONFIG_REPO/wubkat/last-successful-build-to-git-commit.sh)
echo Checking out last successfully built revision "${USE_REV}"

echo "Performing setup::git-checkout step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

pushd $GIT_ROOT
git checkout "${USE_REV}"
popd
echo Revision should now be checked out.

echo "Performing setup::build-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Generating blame information
build-blame $GIT_ROOT $BLAME_ROOT

echo "Performing setup::apt-get-install step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Installing/updating system build dependencies

# Update the apt index
sudo apt-get update

# gtk/install-dependencies below will install a bunch of stuff, but it seems like
# it maybe missed these things I've added after flatpak, but they may also be
# transitive deps of some of the below.  (And now with the return to
# install-dependencies with explicit 22.04 these may not be needed at all, but
# we'll see.)
sudo apt-get install -y libcairo-dev libharfbuzz-dev gi-docgen

echo "Performing setup::install-dependencies step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

# Support for 22.04 seems to have been officially added in
# https://searchfox.org/wubkat/commit/aa960b1a0c7b980efdbc66718239a449b5966a0c
# so we're now using it directly again.
sudo $FILES_ROOT/Tools/gtk/install-dependencies
