#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing setup::download-git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

# Note that our tarball here also includes the flatpak SDK downloads that live
# under git/WebKitBuild/UserFlatpak.
echo Downloading webkit
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing git folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/wubkat.tar.lz4
    lz4 -dc wubkat.tar.lz4 | tar -x
    rm wubkat.tar.lz4
fi
popd

echo "Performing setup::download-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading webkit blame
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/wubkat-blame.tar.lz4
    lz4 -dc wubkat-blame.tar.lz4 | tar -x
    rm wubkat-blame.tar.lz4
fi
popd

echo "Performing setup::git-pull step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Updating git
pushd $GIT_ROOT
git remote prune origin || true
git pull origin main || handle_tree_error "wubkat git pull"
popd

echo "Performing setup::last-successful-build-to-git-commit step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Figuring out what revision to use.
USE_REV=$($CONFIG_REPO/wubkat/last-successful-build-to-git-commit.sh)
echo Checking out last successfully built revision "${USE_REV}"

echo "Performing setup::git-checkout step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

pushd $GIT_ROOT
git checkout "${USE_REV}"
popd
echo Revision should now be checked out.

echo "Performing setup::build-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Generating blame information
build-blame $GIT_ROOT $BLAME_ROOT

echo "Performing setup::apt-get-install step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Installing/updating system build dependencies

# Update the apt index
sudo apt-get update

echo "Performing setup::install-dependencies step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

# For some reasons xdg-dbus-proxy is not in the upstream package list but is
# explicitly depended upon by the configure process.  We also added libcairo-dev
# at some point and there is no harm in still installing it.
sudo "$FILES_ROOT/Tools/gtk/install-dependencies" \
    xdg-dbus-proxy \
    libcairo-dev
