#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# See ../mozilla-central/setup for documentation
# The mozilla-central repo also uploads an updated gecko.tar which
# includes cedar commits, so we don't need our own upload script.

REVISION_TREE=cedar
REVISION_ID=latest

source $CONFIG_REPO/shared/resolve-gecko-revs.sh $REVISION_TREE $REVISION_ID

$CONFIG_REPO/shared/checkout-gecko-repos.sh $REVISION_TREE "cedar" "$INDEXED_HG_REV"

$CONFIG_REPO/shared/fetch-tc-artifacts.sh $REVISION_TREE $INDEXED_HG_REV "$PREEXISTING_HG_REV"
