#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing setup::download-git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading mingw repo
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/mingw.tar
    tar xf mingw.tar
    rm mingw.tar
fi
popd

echo "Performing setup::download-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading mingw blame.
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/mingw-blame.tar
    tar xf mingw-blame.tar
    rm mingw-blame.tar
fi
popd

echo "Performing setup::git-pull step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

MOZ_REV=$(curl -SsfL "https://raw.githubusercontent.com/mozilla-firefox/firefox/refs/heads/main/taskcluster/kinds/fetch/toolchains.yml" | yq -r '.["mingw-w64"].fetch.revision')

echo Updating git
pushd $GIT_ROOT
git pull origin master
git reset --hard ${MOZ_REV}
popd

echo "Performing setup::build-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Generating blame information
build-blame $GIT_ROOT $BLAME_ROOT

echo "Performing setup::git-reset step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

# Check out the blame rev corresponding to MOZ_REV, since the blame
# repo may be ahead of it.

pushd $BLAME_ROOT
BLAME_REV=$(git log -1 --grep=$MOZ_REV --pretty=format:%H)
if [ -z "$BLAME_REV" ]; then
    echo "mingw-moz: Unable to find blame rev for $MOZ_REV"
    exit 1;
fi
git reset --soft $BLAME_REV
popd
