#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing build::indexer-setup step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

## Index the clang-plugin

# Add the special clang flags.
$MOZSEARCH_PATH/scripts/indexer-setup.py > $INDEX_ROOT/config
. $INDEX_ROOT/config

rm -rf $OBJDIR
mkdir -p $OBJDIR

echo "Performing build::make step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

mkdir -p $OBJDIR/clang-plugin
cd $OBJDIR/clang-plugin

CLANG_PLUGIN_DIR=$FILES_ROOT/clang-plugin
# Passing a VPATH will let make find the source files despite us using an objdir.
# Explicitly passing CC and CXX propagates the special clang flags.
make -f $CLANG_PLUGIN_DIR/Makefile VPATH=$CLANG_PLUGIN_DIR CC="$CC" CXX="$CXX"

echo "Performing build::scip-python step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

## Python Indexing

cd $FILES_ROOT
scip-python index --show-progress-rate-limit 0 --project-name python --output python.scip
mv python.scip $INDEX_ROOT

echo "Performing build::rust-analyzer step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

## Rust Indexing

cd $FILES_ROOT
rust-analyzer scip tools
mv index.scip $INDEX_ROOT/rust.scip
