#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Downloading mozsearch repo
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/mozsearch.tar.lz4
    lz4 -dc mozsearch.tar.lz4 | tar -x
    rm mozsearch.tar.lz4
fi
popd

date

echo Downloading mozsearch blame.
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/mozsearch-blame.tar.lz4
    lz4 -dc mozsearch-blame.tar.lz4 | tar -x
    rm mozsearch-blame.tar.lz4
fi
popd

date

echo Updating git
pushd $GIT_ROOT
git pull origin master
# mozsearch uses submodules
git submodule update --init --recursive

popd

echo Generating blame information
build-blame $GIT_ROOT $BLAME_ROOT

date
