#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing setup::download-git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading mozsearch repo
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/mozsearch.tar.lz4
    lz4 -dc mozsearch.tar.lz4 | tar -x
    rm mozsearch.tar.lz4
fi
popd

echo "Performing setup::download-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading mozsearch blame.
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/mozsearch-blame.tar.lz4
    lz4 -dc mozsearch-blame.tar.lz4 | tar -x
    rm mozsearch-blame.tar.lz4
fi
popd

echo "Performing setup::git-pull step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Updating git
pushd $GIT_ROOT
git pull origin master
# mozsearch uses submodules
git submodule update --init --recursive

popd

echo "Performing setup::git-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Generating blame information
build-blame $GIT_ROOT $BLAME_ROOT

echo "Performing setup::codecov2git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

rm -rf "$COVERAGE_ROOT"
mkdir -p "$COVERAGE_ROOT"
HEAD_OID="$(git -C "$GIT_ROOT" rev-parse HEAD)"
HEAD_DATE="$(git -C "$GIT_ROOT" show --no-patch --format=%cI HEAD)"
codecov2git --report "$GIT_ROOT/tests/searchfox/metadata/code-coverage-report.json" --output-repo "$COVERAGE_ROOT" --commit "$HEAD_OID" --date "$HEAD_DATE"
