#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Uploading kaios
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf kaios.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/kaios.tar searchfox.repositories kaios.tar
rm kaios.tar
popd

date

echo Uploading kaios blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf kaios-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/kaios-blame.tar searchfox.repositories kaios-blame.tar
rm kaios-blame.tar
popd

date
