#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing upload::git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading comm-esr102
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf comm-esr102.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/comm-esr102.tar searchfox.repositories comm-esr102.tar
rm comm-esr102.tar
popd

echo "Performing upload::blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading comm-esr102 blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf comm-esr102-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/comm-esr102-blame.tar searchfox.repositories comm-esr102-blame.tar
rm comm-esr102-blame.tar
popd
