#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

# Add the special clang flags.
# See $MOZSEARCH_PATH/scripts/ld-wrapper for WRAPPED_LD and --use-ld-wrapper.
export WRAPPED_LD=ld
$MOZSEARCH_PATH/scripts/indexer-setup.py --use-ld-wrapper > $INDEX_ROOT/config
. $INDEX_ROOT/config

rm -rf $OBJDIR
mkdir -p $OBJDIR

cd $FILES_ROOT
# For git checkouts we need to run autogen.
./autogen.sh

date

cd $OBJDIR
# As per https://www.gnu.org/software/automake/manual/html_node/VPATH-Builds.html
# we want to run configure from the objdir to set up the build tree here.
$FILES_ROOT/configure

date

# And then we can run make here.
make

cd -

date
