#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing setup::download-git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading graphviz repo
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/graphviz.tar.lz4
    lz4 -dc graphviz.tar.lz4 | tar -x
    rm graphviz.tar.lz4
fi
popd

# Temporary fix for the git url.
# This can be deleted once this fix is reflected to the uploaded tarball.
sed -i -e 's|https://gitlab.com/graphviz/graphviz$|https://gitlab.com/graphviz/graphviz.git|' $GIT_ROOT/.git/config

echo "Performing setup::download-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading graphviz blame.
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/graphviz-blame.tar.lz4
    lz4 -dc graphviz-blame.tar.lz4 | tar -x
    rm graphviz-blame.tar.lz4
fi
popd

echo "Performing setup::git-pull step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Updating git
pushd $GIT_ROOT
git pull origin main

popd

echo "Performing setup::build-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Generating blame information
build-blame $GIT_ROOT $BLAME_ROOT

echo "Performing setup::apt-get-install step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

## Since graphviz is going in config5 and we already do wacky package
## installation at runtime, there's no real harm in doing more of it, and this
## avoids us needing to provision autoconf and automake normally.

# Update the apt index
sudo apt-get update

sudo apt-get install -y libtool libltdl-dev automake autoconf bison flex
