#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Downloading comm-central...
pushd $INDEX_ROOT
if [ -d "comm-central" ]
then
    echo "Found pre-existing comm-central folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/comm-central.tar
    tar xf comm-central.tar
    rm comm-central.tar
fi
popd

date

echo Downloading comm-central blame...
pushd $INDEX_ROOT
if [ -d "comm-central-blame" ]
then
    echo "Found pre-existing comm-central-blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/comm-central-blame.tar
    tar xf comm-central-blame.tar
    rm comm-central-blame.tar
fi
popd

date

# We also need to put a copy of mozilla-central into the mozilla/ folder

echo "Downloading mozilla..."
pushd $INDEX_ROOT/comm-central
if [ -d "mozilla" ]
then
    echo "Found pre-existing mozilla subfolder; skipping re-download."
else
    $CONFIG_REPO/shared/fetch-gecko-dev.sh $PWD
    mv gecko-dev mozilla
fi

date

echo Updating git
pushd $GIT_ROOT
git pull
pushd mozilla
# The repo may have been uploaded while checked out to some non-master
# revision (to match the hg revision used in taskcluster)
git checkout master
git pull
popd
popd

echo Generating blame information
python $MOZSEARCH_PATH/blame/transform-repo.py $GIT_ROOT $BLAME_ROOT

date
