#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing setup::download-git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading comm-central...
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing comm-central git folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/comm-central.tar
    tar xf comm-central.tar
    rm comm-central.tar
fi
popd

echo "Performing setup::download-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading comm-central blame...
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/comm-central-blame.tar
    tar xf comm-central-blame.tar
    rm comm-central-blame.tar
fi
popd

echo "Performing setup::download-gecko-git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

# We also need to put a copy of mozilla-central into the mozilla/ folder

echo "Downloading mozilla..."
pushd $INDEX_ROOT/git
if [ -d "mozilla" ]
then
    echo "Found pre-existing mozilla subfolder; skipping re-download."
else
    $CONFIG_REPO/shared/fetch-gecko-tarball.sh gecko $PWD
    mv git mozilla
fi

echo "Performing setup::git-pull step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Updating git
pushd $GIT_ROOT
git pull
pushd mozilla
# The repo may have been uploaded while checked out to some non-master
# revision (to match the hg revision used in taskcluster)
git checkout master
git pull
popd
popd

echo "Performing setup::build-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Generating blame information
build-blame $GIT_ROOT $BLAME_ROOT
