#!/bin/bash

set -e # Errors are fatal
set -x # Show commands

date

echo Uploading comm-central
pushd $INDEX_ROOT
tar --exclude='comm-central/mozilla' -cf comm-central.tar comm-central
python $AWS_ROOT/upload.py $INDEX_ROOT/comm-central.tar searchfox.repositories comm-central.tar
rm comm-central.tar
popd

date

echo Uploading comm-central blame
pushd $INDEX_ROOT
tar cf comm-central-blame.tar comm-central-blame
python $AWS_ROOT/upload.py $INDEX_ROOT/comm-central-blame.tar searchfox.repositories comm-central-blame.tar
rm comm-central-blame.tar
popd

date
