#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Uploading comm-central
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./comm-central
tar --exclude='comm-central/mozilla' -cf comm-central.tar comm-central
$AWS_ROOT/upload.py $INDEX_ROOT/comm-central.tar searchfox.repositories comm-central.tar
rm comm-central.tar
popd

date

echo Uploading comm-central blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./comm-central-blame
tar cf comm-central-blame.tar comm-central-blame
$AWS_ROOT/upload.py $INDEX_ROOT/comm-central-blame.tar searchfox.repositories comm-central-blame.tar
rm comm-central-blame.tar
popd

date
