#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing upload::git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading comm-central
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar --exclude='git/mozilla' -cf comm-central.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/comm-central.tar searchfox.repositories comm-central.tar
rm comm-central.tar
popd

echo "Performing upload::blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading comm-central blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf comm-central-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/comm-central-blame.tar searchfox.repositories comm-central-blame.tar
rm comm-central-blame.tar
popd
