#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Uploading mingw
pushd $INDEX_ROOT
tar cf mingw.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/mingw.tar searchfox.repositories mingw.tar
rm mingw.tar
popd

date

echo Uploading mingw blame
pushd $INDEX_ROOT
tar cf mingw-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/mingw-blame.tar searchfox.repositories mingw-blame.tar
rm mingw-blame.tar
popd

date
