#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing upload::git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading mingw
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf mingw.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/mingw.tar searchfox.repositories mingw.tar
rm mingw.tar
popd

echo "Performing upload::blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading mingw blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf mingw-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/mingw-blame.tar searchfox.repositories mingw-blame.tar
rm mingw-blame.tar
popd
