#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# See ../mozilla-central/setup for documentation

# ESR78 isn't getting any new commits, so we can hard-code the last revision
# for simplicity in checkout-gecko-repos.sh.
# Disclaimer: this rev is actually one behind the current tip which was about
# removing the cron jobs.
$CONFIG_REPO/shared/checkout-gecko-repos.sh "mozilla-esr78" "esr78" "a326cc6a77c6b3ad702ca999b0058693b10e9f58"
