#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing setup::download-git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading rust repo
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/rust.tar
    tar xf rust.tar
    rm rust.tar
fi
popd

echo "Performing setup::download-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading rust blame.
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/rust-blame.tar
    tar xf rust-blame.tar
    rm rust-blame.tar
fi
popd

echo "Performing setup::git-fetch step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Updating git
pushd $GIT_ROOT
git fetch origin main
git checkout origin/main
popd

echo "Performing setup::build-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Generating blame information
build-blame $GIT_ROOT $BLAME_ROOT
