#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Downloading rust repo
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/rust.tar
    tar xf rust.tar
    rm rust.tar
fi
popd

date

echo Downloading rust blame.
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/rust-blame.tar
    tar xf rust-blame.tar
    rm rust-blame.tar
fi
popd

date

echo Updating git
pushd $GIT_ROOT
git fetch origin main
git checkout origin/main
popd

echo Generating blame information
build-blame $GIT_ROOT $BLAME_ROOT

date
