#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Uploading rust
pushd $INDEX_ROOT
tar cf rust.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/rust.tar searchfox.repositories rust.tar
rm rust.tar
popd

date

echo Uploading rust blame
pushd $INDEX_ROOT
tar cf rust-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/rust-blame.tar searchfox.repositories rust-blame.tar
rm rust-blame.tar
popd

date
