#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing upload::git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading rust
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf rust.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/rust.tar searchfox.repositories rust.tar
rm rust.tar
popd

echo "Performing upload::blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading rust blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf rust-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/rust-blame.tar searchfox.repositories rust-blame.tar
rm rust-blame.tar
popd
