#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Uploading comm-release
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf comm-release.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/comm-release.tar searchfox.repositories comm-release.tar
rm comm-release.tar
popd

date

echo Uploading comm-release blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf comm-release-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/comm-release-blame.tar searchfox.repositories comm-release-blame.tar
rm comm-release-blame.tar
popd

date
