#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Downloading comm-esr60 repo
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/comm-esr60.tar
    tar xf comm-esr60.tar
    rm comm-esr60.tar
fi
popd

date

echo Downloading comm-esr60 blame.
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/comm-esr60-blame.tar
    tar xf comm-esr60-blame.tar
    rm comm-esr60-blame.tar
fi
popd

date

echo Updating git
pushd $GIT_ROOT
git pull
popd

echo Generating blame information
build-blame $GIT_ROOT $BLAME_ROOT

date
