#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing upload::git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading mozilla-mobile
pushd $INDEX_ROOT

echo "Running maintenance on mozilla-mobile submodules..."
pushd ./git
git submodule foreach --recursive "${CONFIG_REPO}/shared/git-maintenance.sh \$PWD"
popd
echo "Running maintenance on mozilla-mobile supermodule..."
$CONFIG_REPO/shared/git-maintenance.sh ./git
echo "Maintenance complete!"

tar cf mozilla-mobile.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/mozilla-mobile.tar searchfox.repositories mozilla-mobile.tar
rm mozilla-mobile.tar

popd
