#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Downloading v-c-t repo
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/version-control-tools.tar
    tar xf version-control-tools.tar
    rm version-control-tools.tar
fi
popd

date

echo Downloading v-c-t blame.
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/version-control-tools-blame.tar
    tar xf version-control-tools-blame.tar
    rm version-control-tools-blame.tar
fi
popd

date

echo Updating git
pushd $GIT_ROOT
git pull
popd

echo Generating blame information
build-blame $GIT_ROOT $BLAME_ROOT

date
