#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing upload::git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading v-c-t
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf version-control-tools.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/version-control-tools.tar searchfox.repositories version-control-tools.tar
rm version-control-tools.tar
popd

echo "Performing upload::blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading v-c-t blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf version-control-tools-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/version-control-tools-blame.tar searchfox.repositories version-control-tools-blame.tar
rm version-control-tools-blame.tar
popd
