#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Uploading v-c-t
pushd $INDEX_ROOT
tar cf version-control-tools.tar git
python $AWS_ROOT/upload.py $INDEX_ROOT/version-control-tools.tar searchfox.repositories version-control-tools.tar
rm version-control-tools.tar
popd

date

echo Uploading v-c-t blame
pushd $INDEX_ROOT
tar cf version-control-tools-blame.tar blame
python $AWS_ROOT/upload.py $INDEX_ROOT/version-control-tools-blame.tar searchfox.repositories version-control-tools-blame.tar
rm version-control-tools-blame.tar
popd

date
