#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Downloading mozilla-vpn-client repo
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/mozilla-vpn-client.tar
    tar xf mozilla-vpn-client.tar
    rm mozilla-vpn-client.tar
fi
popd

date

echo Downloading mozilla-vpn-client blame.
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/mozilla-vpn-client-blame.tar
    tar xf mozilla-vpn-client-blame.tar
    rm mozilla-vpn-client-blame.tar
fi
popd

date

echo Updating git
pushd $GIT_ROOT
git pull
popd

echo Generating blame information
$MOZSEARCH_PATH/tools/target/release/build-blame $GIT_ROOT $BLAME_ROOT

date
