#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing upload::git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading mozilla-vpn-client
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf mozilla-vpn-client.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/mozilla-vpn-client.tar searchfox.repositories mozilla-vpn-client.tar
rm mozilla-vpn-client.tar
popd

echo "Performing upload::blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading mozilla-vpn-client blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf mozilla-vpn-client-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/mozilla-vpn-client-blame.tar searchfox.repositories mozilla-vpn-client-blame.tar
rm mozilla-vpn-client-blame.tar
popd
