#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# We reuse the mozsearch tarball for downloads; we are not responsible for
# uploading anything.
