#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# See ../mozilla-central/setup for documentation

# ESR102 isn't getting any new commits, so we can hard-code the last revision
# for simplicity in checkout-gecko-repos.sh.
$CONFIG_REPO/shared/checkout-gecko-repos.sh "mozilla-esr102" "esr102" "9df9599ab93f731765afd98cb450c8ffdd3eafdf"
