#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# See ../mozilla-central/setup for documentation

REVISION_TREE=mozilla-esr140
REVISION_ID=latest

source $CONFIG_REPO/firefox-shared/resolve-gecko-revs.sh $REVISION_TREE $REVISION_ID

$CONFIG_REPO/firefox-shared/checkout-gecko-repos.sh $REVISION_TREE "esr140" "$INDEXED_HG_REV"

$CONFIG_REPO/firefox-shared/fetch-tc-artifacts.sh $REVISION_TREE $INDEXED_HG_REV "$PREEXISTING_HG_REV"
