#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

pushd $INDEX_ROOT
$CONFIG_REPO/firefox-shared/process-gecko-analysis.sh
popd

echo "Performing build::scip-python step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

## Analyze the unified python corpus
pushd $GIT_ROOT

# Build a pyrightconfig.json config (config docs are at
# https://microsoft.github.io/pyright/#/configuration).
#
# In order to reduce the memory pressure, we split the files in to two chunks.
# First one is the top-level directory, excluding the web platform test and some
# third party internal things.
# Second one is the web platform test.
#
# Specific settings:
# - verboseOutput: when true, this will print a lot of output about module
#   resolution failures and the paths it tried.  Unfortunately this does not
#   really help with understanding what is going on when the indexing process
#   just sits there and gobbles up CPU.
# - include: Just specify the target directory
# - extraPaths: We include all directories for path resolution purposes
# - exclude: For the top-level directory, exclude some heavy/unrelated things
#
# For the top-level directory, there are ~7000 files.  Processing all of them
# consumes a lot of memory, thus we specify --max-old-space-size to increase
# the memory limit.
# At the point of this commit, this takes 7.9GB.

cat <<EOF > __pyright_exclude_paths.txt
testing/web-platform
third_party/chromium/build
third_party/libwebrtc
third_party/python/aiohttp/examples
third_party/python/cbor2
third_party/python/dlmanager/examples
third_party/python/gyp/test
third_party/python/pip/pip/_internal
third_party/python/pip/pip/_vendor
third_party/python/ply/example
third_party/python/python-hglib/examples
third_party/python/pyyaml/examples
third_party/python/setuptools/setuptools/_vendor
third_party/python/setuptools/setuptools/_distutils/tests
third_party/rust
EOF

jo verboseOutput=false \
  include=$(echo "." | jo -a) \
  extraPaths=$(git ls-files '*.py' | xargs -n1 dirname | sort | uniq | grep -vf __pyright_exclude_paths.txt | jo -a) \
  exclude=$(cat __pyright_exclude_paths.txt | jo -a) \
  > pyrightconfig.json

# Absolute paths aren't treated as absolute but instead concatenated, so we need
# to use just a filename and then move it after.
NODE_OPTIONS="--max-old-space-size=10240" scip-python index --show-progress-rate-limit 0 --project-name python --output python.scip
mv python.scip $INDEX_ROOT

jo verboseOutput=false \
  include=$(echo testing/web-platform | jo -a) \
  extraPaths=$(echo testing/web-platform | jo -a) \
  > pyrightconfig.json

NODE_OPTIONS="--max-old-space-size=10240" scip-python index --show-progress-rate-limit 0 --project-name python --output python2.scip
mv python2.scip $INDEX_ROOT

popd
