#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# This defaults to the most recent searchfox indexing run for mozilla-central
# which is still the name of the firefox-main tree for build purposes.
BUILD_REVISION_TREE=mozilla-central
BUILD_REVISION_ID=latest

TC_ROOT_URL=https://firefox-ci-tc.services.mozilla.com
TC_INDEX_API_URL=${TC_ROOT_URL}/api/index/v1/task

# The next line populates the INDEXED_HG_REV and PREEXISTING_HG_REV env vars.
# Note that PREEXISTING_HG_REV will generally be empty in production.
source $CONFIG_REPO/firefox-shared/resolve-gecko-revs.sh $BUILD_REVISION_TREE $BUILD_REVISION_ID

$CONFIG_REPO/firefox-shared/checkout-gecko-repos.sh $BUILD_REVISION_TREE "main" "$INDEXED_HG_REV"

$CONFIG_REPO/firefox-shared/fetch-tc-artifacts.sh $BUILD_REVISION_TREE $INDEXED_HG_REV "$PREEXISTING_HG_REV"

echo "Performing setup::codecov2git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"
if [ ! -d "$COVERAGE_ROOT" ]; then
    # Can't directly clone https://searchfox.repositories.s3.amazonaws.com/firefox-main-coverage.bundle because the bucket has got a . in its name.
    if [[ ! -f "firefox-main-coverage.bundle" ]]; then
        aws s3 cp s3://searchfox.repositories/firefox-main-coverage.bundle . --no-sign-request
    fi
    git clone --mirror firefox-main-coverage.bundle "$COVERAGE_ROOT"
    rm firefox-main-coverage.bundle
fi

COVERAGE_SINCE=$(date --iso-8601=seconds --date='last month')
COVERAGE_BRANCH="all/all"
codecov2git_gcloud --firefox-repo "$GIT_ROOT" --output-repo "$COVERAGE_ROOT" --since "$COVERAGE_SINCE" --branch "$COVERAGE_BRANCH"

# Note that only $SHARED_BARE_GIT_ROOT diverges from the worktree $GIT_ROOT.
# We use these paths for clarity/consistency that we're working in bare-repo space.
SHARED_BARE_GIT_ROOT=$SHARED_ROOT/git
SHARED_BARE_OLDGIT_ROOT=$SHARED_ROOT/oldgit
SHARED_BARE_BLAME_ROOT=$SHARED_ROOT/blame

# Also generate blame for some other branches, because the blame repo is
# shared by those branches. We do this here instead of in e.g. ../firefox-beta/setup
# because it's best to have only one indexer instance responsible for updating and
# pushing the tarball to S3, to avoid accidental clobbers.
#

# --- Generate Branches with old searchfox permalink support
# DO NOT ADD NEW BRANCHES HERE AS-IS, Either create a forked version of this logic
# without use of `--old-cinnabar-repo-path` or remove that use here.  Specifically,
# we need to have fully moved off of the old mozilla-* branches for the below
# branches.
echo "Performing setup::build-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"
for BRANCH in main beta release esr140 esr128 esr115; do
    echo "Generating blame information for $BRANCH..."
    # Try and start from an existing blame branch if this is a new branch.  New
    # esr branches should look most like the release branch, and we expect other
    # branches in the future will probably be feature branches based off of
    # main.
    #
    # Some interesting historical notes for the initial firefox-* conversions:
    # - Building blame for "beta" off of "main" required ingesting blame for
    #   66,408 revisions.
    # - Building blame for "release" off of "beta" required ingesting blame for
    #   5,415 revisions.
    # - Building blame for "esr140" off of "release" required ingesting blame for
    #   227 revisions.
    # - Building blame for "esr128" off of "release" required ingesting blame for
    #   965 revisions.
    if [[ "$BRANCH" == esr* ]]; then
        BASEBRANCH="release"
    else
        BASEBRANCH="main"
    fi
    git -C "$SHARED_BARE_BLAME_ROOT" show-ref --verify --quiet "refs/heads/${BRANCH}" || git -C "$SHARED_BARE_BLAME_ROOT" branch "${BRANCH}" "${BASEBRANCH}"
    build-blame "$SHARED_BARE_GIT_ROOT" "$SHARED_BARE_BLAME_ROOT" --blame-ref="refs/heads/$BRANCH" --old-cinnabar-repo-path "$SHARED_BARE_OLDGIT_ROOT"
done

for BRANCH in enterprise-main; do
    echo "Generating blame information for $BRANCH..."

    BASEBRANCH="main"

    git -C "$SHARED_BARE_BLAME_ROOT" show-ref --verify --quiet "refs/heads/${BRANCH}" || git -C "$SHARED_BARE_BLAME_ROOT" branch "${BRANCH}" "${BASEBRANCH}"
    build-blame "$SHARED_BARE_GIT_ROOT" "$SHARED_BARE_BLAME_ROOT" --blame-ref="refs/heads/$BRANCH"
done
