#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

pushd $GIT_ROOT
rust-analyzer scip .
mkdir -p $OBJDIR
mv index.scip $OBJDIR/rust.scip
popd
