#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing build::rust-analyzer step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

pushd $GIT_ROOT
rust-analyzer scip .
mkdir -p $OBJDIR
mv index.scip $OBJDIR/rust.scip
popd
