#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Downloading WHATWG HTML repo
pushd $INDEX_ROOT
if [ -d "html" ]
then
    echo "Found pre-existing html folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/whatwg-html-git.tar
    tar xf whatwg-html-git.tar
    rm whatwg-html-git.tar
fi
popd

date

echo Downloading WHATWG HTML blame
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/whatwg-html-blame.tar
    tar xf whatwg-html-blame.tar
    rm whatwg-html-blame.tar
fi
popd

date

echo Updating git
pushd $GIT_ROOT
git pull
popd

echo Generating blame information
$MOZSEARCH_PATH/tools/target/release/build-blame $GIT_ROOT $BLAME_ROOT

date
