#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing setup::download-git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading WHATWG HTML repo
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing git folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/whatwg-html.tar
    tar xf whatwg-html.tar
    rm whatwg-html.tar
fi
popd

echo "Performing setup::download-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Downloading WHATWG HTML blame
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/whatwg-html-blame.tar
    tar xf whatwg-html-blame.tar
    rm whatwg-html-blame.tar
fi
popd

echo "Performing setup::git-pull step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Updating git
pushd $GIT_ROOT
git pull
popd

echo "Performing setup::git-blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Generating blame information
build-blame $GIT_ROOT $BLAME_ROOT
