#!/bin/bash

set -e # Errors are fatal
set -x # Show commands

date

echo Uploading WHATWG HTML
pushd $INDEX_ROOT
tar cf whatwg-html-git.tar html
python $AWS_ROOT/upload.py $INDEX_ROOT/whatwg-html-git.tar searchfox.repositories whatwg-html-git.tar
rm whatwg-html-git.tar
popd

date

echo Uploading WHATWG HTML blame
pushd $INDEX_ROOT
tar cf whatwg-html-blame.tar blame
python $AWS_ROOT/upload.py $INDEX_ROOT/whatwg-html-blame.tar searchfox.repositories whatwg-html-blame.tar
rm whatwg-html-blame.tar
popd

date
