#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

echo "Performing upload::git step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading WHATWG HTML
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf whatwg-html.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/whatwg-html.tar searchfox.repositories whatwg-html.tar
rm whatwg-html.tar
popd

echo "Performing upload::blame step for $TREE_NAME : $(date +"%Y-%m-%dT%H:%M:%S%z")"

echo Uploading WHATWG HTML blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf whatwg-html-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/whatwg-html-blame.tar searchfox.repositories whatwg-html-blame.tar
rm whatwg-html-blame.tar
popd
