#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Downloading comm-esr140 repo
pushd $INDEX_ROOT
if [ -d "git" ]
then
    echo "Found pre-existing folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/comm-esr140.tar.lz4
    lz4 -dc comm-esr140.tar.lz4 | tar -x
    rm comm-esr140.tar.lz4
fi
popd

date

echo Downloading comm-esr140 blame.
pushd $INDEX_ROOT
if [ -d "blame" ]
then
    echo "Found pre-existing blame folder; skipping re-download."
else
    wget -nv https://s3-us-west-2.amazonaws.com/searchfox.repositories/comm-esr140-blame.tar.lz4
    lz4 -dc comm-esr140-blame.tar.lz4 | tar -x
    rm comm-esr140-blame.tar.lz4
fi
popd

date

echo Updating git
pushd $GIT_ROOT
git pull
popd

echo Generating blame information
build-blame $GIT_ROOT $BLAME_ROOT

date
