#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Uploading comm-esr91
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf comm-esr91.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/comm-esr91.tar searchfox.repositories comm-esr91.tar
rm comm-esr91.tar
popd

date

echo Uploading comm-esr91 blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf comm-esr91-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/comm-esr91-blame.tar searchfox.repositories comm-esr91-blame.tar
rm comm-esr91-blame.tar
popd

date
