#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Uploading l10n
pushd $INDEX_ROOT

echo "Running maintenance on l10n submodules..."
for submod in ./git/*; do
    $CONFIG_REPO/shared/git-maintenance.sh "${submod}"
done
echo "Running maintenance on l10n supermodule..."
$CONFIG_REPO/shared/git-maintenance.sh ./git
echo "Maintenance complete!"

tar cf l10n.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/l10n.tar searchfox.repositories l10n.tar
rm l10n.tar

popd

date
