#!/bin/bash

set -e # Errors are fatal
set -x # Show commands

date

cat > $INDEX_ROOT/mozconfig <<EOF
. \$topsrcdir/browser/config/mozconfig
mk_add_options MOZ_OBJDIR=$OBJDIR
ac_add_options --enable-debug
ac_add_options --enable-optimize
ac_add_options --enable-gczeal
ac_add_options --without-ccache
ac_add_options --enable-js-shell
EOF

mkdir -p $OBJDIR

# Add the special clang flags.
$MOZSEARCH_PATH/scripts/indexer-setup.py >> $INDEX_ROOT/mozconfig

cd $FILES_ROOT
if [ -f "$INDEX_ROOT/target.mozsearch-index.zip" ]
then
    echo "Skipping build, since we have analysis data from TaskCluster"
else
    MOZCONFIG=$INDEX_ROOT/mozconfig ./mach bootstrap --application-choice=browser --no-interactive --no-system-changes
    MOZCONFIG=$INDEX_ROOT/mozconfig ./mach build
    # Delete the ~1.8 Gb of toolchains that we don't need after this (we'll need the space to write big files in /tmp later)
    rm -rf $HOME/.mozbuild
fi
cd -

date
