#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

pushd $INDEX_ROOT
$CONFIG_REPO/shared/process-gecko-analysis.sh
popd

date

# Analyze the unified python corpus
pushd $GIT_ROOT/python
# Absolute paths aren't treated as absolute but instead concatenated, so we need
# to use just a filename and then move it after.
mise exec nodejs@18 -- scip-python index --project-name python --output python.scip
# XXX note that we currently don't consume this output; there needs to be an entry
# in the config.json for this to work, but unfortunately because of
# https://github.com/sourcegraph/scip-python/issues/148
# the SCIP output is currently not usable.
mv python.scip $INDEX_ROOT
popd

date
