#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

# Edit this to e.g. try.revision.ee64db93dcc149da9313460317257b8c42eec5b2 or whatever
# to test other revisions.
# This defaults to the most recent searchfox indexing run for mozilla-central.
REVISION_TREE=mozilla-central       # replace with e.g. 'try' for testing
REVISION_ID=latest                  # replace with e.g. 'revision.ee64db93dcc149da9313460317257b8c42eec5b2' for testing

# The next line populates the INDEXED_HG_REV env var.
source $CONFIG_REPO/shared/resolve-gecko-revs.sh $REVISION_TREE $REVISION_ID

$CONFIG_REPO/shared/checkout-gecko-repos.sh $REVISION_TREE "master" "$INDEXED_HG_REV"

pushd $INDEX_ROOT
$CONFIG_REPO/shared/fetch-tc-artifacts.sh $REVISION_TREE $INDEXED_HG_REV
popd

date

# Also generate blame for some other branches, because the gecko-blame repo is
# shared by those branches. We do this here instead of in e.g. ../mozilla-beta/setup
# because it's best to have only one indexer instance responsible for updating and
# pushing the tarball to S3, to avoid accidental clobbers. It's not a great situation
# architecturally, but it's better for performance.
for BRANCH in beta release esr68 esr60 esr45 esr31 esr17; do
    echo "Updating gecko-dev branch $BRANCH to latest from upstream..."
    pushd $GIT_ROOT
    git branch -f $BRANCH origin/$BRANCH || git branch -f $BRANCH projects/$BRANCH
    popd
    echo "Generating blame information for $BRANCH..."
    CINNABAR=1 BLAME_REF="refs/heads/$BRANCH" python $MOZSEARCH_PATH/blame/transform-repo.py $GIT_ROOT $BLAME_ROOT
done

date
