#!/bin/bash

set -e # Errors are fatal
set -x # Show commands

echo Updating mercurial
pushd $HG_ROOT
hg pull -u
popd

echo Updating git
pushd $TREE_ROOT
git pull
popd

echo Generating blame information
python $MOZSEARCH_PATH/blame/transform-repo.py $TREE_ROOT $BLAME_ROOT $HG_ROOT
