#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Uploading Gecko
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./gecko-dev
tar cf gecko.tar gecko-dev
$AWS_ROOT/upload.py $INDEX_ROOT/gecko.tar searchfox.repositories gecko.tar
rm gecko.tar
popd

date

echo Uploading Gecko blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./gecko-blame
tar cf gecko-blame.tar gecko-blame
$AWS_ROOT/upload.py $INDEX_ROOT/gecko-blame.tar searchfox.repositories gecko-blame.tar
rm gecko-blame.tar
popd

date
