#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# See ../mozilla-central/setup for documentation

REVISION_TREE=mozilla-esr68
REVISION_ID=latest
TRY_GIT_REV=
export INDEX_RUSTLIB=yes

date

source $CONFIG_REPO/shared/resolve-gecko-revs.sh $REVISION_TREE $REVISION_ID

date

$CONFIG_REPO/shared/checkout-gecko-repos.sh "esr68" "$INDEXED_GIT_REV"

date

if [ -n "$INDEXED_GIT_REV" ]; then
    pushd $INDEX_ROOT
    $CONFIG_REPO/shared/fetch-tc-artifacts.sh $REVISION_TREE $INDEXED_HG_REV
    popd

    date
else
    echo "ERROR: Unable to find git equivalent for hg rev $INDEXED_HG_REV; please fix the mapper and retry."
    exit 1
fi
