#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

# We no longer build NSS for semantic purposes.  The tentative plan would be for
# NSS to run the clang indexer on its taskcluster instance and generate
# artifacts like we do for m-c trees.
