#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

echo Uploading NSPR
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./git
tar cf nss.tar git
$AWS_ROOT/upload.py $INDEX_ROOT/nss.tar searchfox.repositories nss.tar
rm nss.tar
popd

date

echo Uploading NSS blame
pushd $INDEX_ROOT
$CONFIG_REPO/shared/git-maintenance.sh ./blame
tar cf nss-blame.tar blame
$AWS_ROOT/upload.py $INDEX_ROOT/nss-blame.tar searchfox.repositories nss-blame.tar
rm nss-blame.tar
popd

date
